### ISSUE TITLE
Games do not appear to be synced with a local server

### ISSUE THREAD

**Issue by intcreator** [cs340tabyu/cs340Winter2017#100]
When the client is first opened after restarting the server, the game hub shows 10 games instead of the expected 3.  Where are these games stored?  Why are they there?

Games created with another client show up on this client and on Swagger.  Games created with this client do not show up another client or on Swagger.

The client appears to run independent of a local server.  Games one of our team members created appeared on the client of another team member.  The client stopped working when one team member turned off his computer's wifi.

**Comment by smithskyler** [comment]
Games are supposed to run independent of the server. The server can be run on someone else's computer. That's spec as far as I know. When you run your game, you implicitly or explicitly set the server port depending on how you start it. If multiple players have connected to the same server, then their games will be visible to the others. You should check to see how each player is running the client. Are some of you specifying the server while the others aren't?

If this even is a bug, I would say that it's P3, since it doesn't crash or keep you from playing a game.

**Comment by intcreator** [comment]
So you set the default port to something else?  What server is being run?  Is it on one of your machines?  It appears to be connecting over the Internet...

**Comment by smithskyler** [comment]
It should be connecting over the internet; we were told to make sure that it could run on a different machine. You can specify the port as per spec through the command line. Last time I checked, the default is a remote server running on a machine we set up.

**Comment by smithskyler** [comment]
The spec says it should handle `java -jar catan-client <host> <port>`

You should use that.

This isn't a bug.
