### ISSUE TITLE
Cannot add AI players

### ISSUE THREAD

**Issue by spencerolsen** [cs340tabyu/cs340Winter2017#11]
Steps to reproduce:
1. Login as Sam
2. Create a new game
3. Join that game and select a color
4. The PlayerWaiting view pops up with the option to add a computer player
5. Clicking the button to add a computer player causes the modal to close and reopen, but no AI player has been added

**Comment by tylercr2** [comment]
This doesn't block gameplay, its just a missing feature, not sure I would label this P2. Also duplicate with another bug.

**Comment by jerekeith2** [comment]
As you are unable to actually play your created game with AI's, you are blocked.  The player becomes stuck in the Player Waiting Screen unable to do anything without closing the client. If it was a missing feature, the create game button would be disabled so the user wouldn't be lead into a frozen game state.

Which issue is this duplicate with?

**Comment by tylercr2** [comment]
But this isn't the case. We aren't able to add AI, so you can't create a game yourself with AI. The default server configuration does include a game where pete is in a game with 3 AI, and you can play that without getting blocked. You are saying that not being able to add AI blocks gameplay, which it doesn't. You can still play the game with 4 players, you can't add AI, which is a bug/missing feature, but it in no way blocks gameplay. You just need to open other clients and join the game. This would be a P3 / P4 depending on your interpretation, because not being able to add AI does not prevent the game from progressing, nor does it cause the game to crash or halt. It simply doesn't add the AI to your game when you click the button.

Also I meant this was duplicate with #40 as it in my mind was the same thing, we don't have the option to add AI. But I could see how not listing the AI / not adding could be considered different.

**Comment by jerekeith2** [comment]
How is the user supposed to know this is an unimplemented feature?

They don't. If the user want's to create his own game with new AI, and can't proceed with that action, he can't play the game.  He is blocked from game play. 

I understand your thinking with issue #40 being similar.  However this is black box testing, as a tester we can't make assumptions on whether something is implemented or not.  If it doesn't work, it's a bug. If it halts progress and prevents "moving on with the game", it's a p2.

This might all root to differing definitions of "gameplay". If you feel wronged, you may by all means take it up with the TAs.
