### ISSUE TITLE
Incorrect restrictions on road placement in setup

### ISSUE THREAD

**Issue by jjaywhitaker** [cs340tabyu/cs340Winter2017#132]
When building second road I can't place it next to first road or first settlement.

**Comment by mike0256** [comment]
Would you mind attaching an image of what you are trying to do? From your description is sounds like you're trying to place the road in a way that wouldn't allow for placing the second settlement in a location that doesn't violate the distance rule. i.e. The second road will never be allowed to be placed connecting directly to the first settlement because there would be no place for the second settlement that doesn't break the distance rule and still enforces the rule that the second settlement must be connected to the second road.
Then as far as not being able to place the second road next to the first one I'd like to see an image of exactly what you are trying to do because that road must be placed in a location that allows for the settlement to be connected to it without violating the distance rule. Thanks.

**Comment by cojoco** [comment]
I'm tentatively calling this invalid unless we get clarification.
