### ISSUE TITLE
Pasting a PowerPoint into the chat message field breaks the game when you send it XD

### ISSUE THREAD

**Issue by alexandergunnarson** [cs340tabyu/cs340Winter2017#183]
1. Open any PowerPoint (or any binary) in text editor
2. Copy and then paste into chat message field
3. Wait a bit :D
4. Press send and wait for everything to blow up!
   ![image](https://cloud.githubusercontent.com/assets/4691106/19746645/4e574ad2-9ba5-11e6-8722-5f3098442261.png)

**Comment by mhnsn** [comment]
That's...impressive bug testing?

**Comment by ringmaster217** [comment]
This is a really dumb bug that somebody decided to log against us to try and be funny, yet failed miserably.

**Comment by dansteren** [comment]
@ringmaster217 

First off, I do think it is a little funny. Was it a little overkill? yes. I wouldn't have thought to make sure no one sends a powerpoint through chat. Did we expect it to actually shut down your server? no. This wasn't malicious, just a thorough test. That being said, I'm not sure how I would have reacted if a team had done this to us, so let me explain a little further.

The reason we logged this issue is not because you should support powerpoint file transfers, but because you should sanitize inputs. That's basic defensive programming. Your downfall was not the powerpoint data format, but rather, that the amount of data we sent was very large. If you don't limit your users input then you are just opening your server up to exploits.

I'm not going to remove the invalid tag, but I think you should discuss the validity of this issue with the TAs. It's probably not a P1 because we are only testing the client code, but if this were phase 3 it would definitely be a show stopper.

**Comment by intcreator** [comment]
The fact that invalid input caused the server to shut down to me is a P1.  Imagine if something like this happened in the industry—would you really want your entire server brought to its knees because someone (whether maliciously or as a joke) simply pasted binary plaintext into one of your fields?  This is a serious issue.  I recommend you address it when you refactor your project.

**Comment by smithskyler** [comment]
The TAs said it's not in spec.
