### ISSUE TITLE
Domestic Trade with AI  freezes at "Waiting for Trade to Go Through"

### ISSUE THREAD

**Issue by dolson25** [cs340tabyu/cs340Winter2017#246]

**Comment by Napper15** [comment]
This only occurs when the trade fails due to the AI not having enough resources

**Comment by dolson25** [comment]
so still a bug?

**Comment by cgrange** [comment]
This is actually another bug that forced this error. It has to do with the poller. We assumed that every time a trade would be made there would be a few version updates. (you make a trade offer and there is a new version than it is accepted or rejected and a new version, this second version of the model is what notifies observers) Since the AI is on the server and the info is updated there we never get that second model change which would notify observers which would close the modal. Therefore I am going to mark this as invalid since it was a fix in the poller and not a fix in the domestic trade controller

**Comment by dolson25** [comment]
It is still my opinion that it was a bug in part of the client and that it could have been fixed during testing and that it halts gameplay
