### ISSUE TITLE
Cannot use different hostname/port

### ISSUE THREAD

**Issue by kupiakos** [cs340tabyu/cs340Winter2017#286]
If the server is started on a different port, one can't use

```
java -jar catan-client.jar localhost <port>
```

to use that port to connect to the server.

**Comment by derbraun** [comment]
@kupiakos Could you please elaborate on this? The ant server command sets up the demo server on port 8081. What server were you running? The TAs clearly stated in their emails that phase 2 testing should use the demo server.

Further more, the spec doesn't ask us to enable this kind of command until Phase 3.

**Comment by kupiakos** [comment]
@derbraun The demo server can run on any hostname/port you choose; it's a command line argument for the server JAR. The defaults are just `localhost` and `8081`.

[Phase 2 Spec PDF](https://students.cs.byu.edu/~cs340ta/fall2016/group_project/Phase2Spec.pdf), Implementation and Testing section at the end:

```
3. Create command line parameters on your client for both the host and port on which the
Catan server is running. Modify the ant target “our-client” to support passing these
parameters into the target with the names “host” and “port” respectively. You should be
able to specify the host and port with either ANT or using the java command as specified
below.
4. [...] After unzipping your zip file, testers should be able to run your Catan
client by entering the following command: java -jar catan-client.jar <host>
<port>
```

Where are you seeing Phase 3 being the first phase to require this? EDIT: I have noticed that the Phase 3 Spec does say to implement this, but it's also mentioned pretty explicitly in Phase 2. The documents are not very clear on that.

**Comment by derbraun** [comment]
I see that now. Thank you for pointing this out. We clearly did not implement our our-client command  to allow this.

That being said, the ant client, despite this command only runs on port 8081, even if you specify otherwise.  See graphic below.

![ant server port](https://cloud.githubusercontent.com/assets/21980276/19788984/3bd2ea0a-9c69-11e6-8d42-4092b94143b1.png)
the fuser <port>/<tcp/udp> command lists all services listening on listed port.

Further more, I have run the ant server and client on port 8888, as specified, and got normal behavior.
I as such, I would say that this does NOT affect game play. Moving this to P4.

![running client on different port](https://cloud.githubusercontent.com/assets/21980276/19789057/d61da1a4-9c69-11e6-9891-4d80b56fa382.png)

**Comment by kupiakos** [comment]
In the demo directory run `java -jar server.jar 8085 gameplay ug`.
It will run on port 8085. The ant targets are not indicative of the actual program and must be changed in order to change execution.

Not being able to access a server on a different port is directly against the spec and prevents log in if the server is on a different port. "Cannot log in" is a P2 error, even if it requires something different, as it directly blocks gameplay. If this bug is not P3 it's P2.

**Comment by derbraun** [comment]
Thanks for the command, I will start working on it. 

For the record, the demo doesn't have this ability, so it is confusing all over the place

![screenshot from 2016-10-27 18-35-20](https://cloud.githubusercontent.com/assets/21980276/19790454/858fc90e-9c75-11e6-8127-a22d741be54d.png)

**Comment by derbraun** [comment]
Fixed and re-tested command using java -jar server.jar 8085 gameplay ug in the demo directory

People can now register and play game
