### ISSUE TITLE
If a user exits a game, and then rejoins, the map does not load.

### ISSUE THREAD

**Issue by mclements37** [cs340tabyu/cs340Winter2017#299]
![screen shot 2016-10-26 at 7 32 58 pm](https://cloud.githubusercontent.com/assets/21322207/19751029/79845304-9bb3-11e6-8b6b-b18229a02fa0.png)

**Comment by mclements37** [comment]
I think this would technically be a P2 blocking game play, however I am just listing it as a P3 since if I never log out, then this error would never be a problem.

**Comment by dansteren** [comment]
hum... This issue is a little vague. I don't know what else surrounded the creation of this bug. Meaning, I just created a new game, added settlements, and got to the first roll. I then exited the game, and came back in and I was right where it left off, asking me to roll.

**Comment by dansteren** [comment]
I'm wondering if the map was there and the window just needed to be resized... we've had that issue before.

**Comment by dansteren** [comment]
Ok, I cannot recreate this issue. I've tried during the setup phase, during regular gameplay, with 3 AIs, with two people and 2 AIs... I cannot get this to happen. My guess is that map was getting refreshed with our infinite loop and since we've fixed that the problem has gone away. I'm gonna close this for now, but if someone experiences this please document better the circumstances under which it occurred.
