### ISSUE TITLE
Flickering views

### ISSUE THREAD

**Issue by mclements37** [cs340tabyu/cs340Winter2017#318]
We think the reason it keeps flashing is because your poller is going every fourth of a second. This doesn't effect the actual rules of the game, but the constant flashing makes it incredibly difficult to do anything with an overlay, like selecting cards to discard.

![image](https://cloud.githubusercontent.com/assets/21322207/19752236/11eba8f4-9bb9-11e6-925c-c1ceea8d574c.png)

**Comment by SierraD012** [comment]
I'm seeing the same issue. It looks like the poller is asking for the model (/model) every 2 seconds like it should, but it is also asking for the list of games (/games/list) every 1/4 sec or so. Once the user logs in to the main game and starts playing, the only thing the game needs from the server is the model. So you can stop the /games/list poll once they've started the game.

**Comment by SierraD012** [comment]
Update: It appears that the /games/list command is being sent every 2 seconds (along with the /model command) just like it should be up until the actual gameplay (setup phases) starts. At that point, it looks like the commands each double in frequency, most notably the /games/list command, which isn't even necessary during actual gameplay. Seeing this makes me wonder if somehow a second instance of your ServerPoller was instantiated when the gameplay starts, so that both pollers are sending requests to the server simultaneously??

**Comment by dansteren** [comment]
We are dispatching from inside a dispatch. Jordan is fixing this right now.
