### ISSUE TITLE
Halts at setup for new games

### ISSUE THREAD

**Issue by daviscodesbugs** [cs340tabyu/cs340Winter2017#34]
After creating a new game, immediately rejoin it.
Add 3 AI.

The game shows the map, but no setup modal appears. This may be related to the issue where you see the setup modal blink when joining an empty game. (See issue #35 )

**Comment by mhnsn** [comment]
Note that closing the client and re-joining does allow the player to continue.

**Comment by csydvs** [comment]
This turns out to be a fairly minor bug, since you can just re-set the client. Our issue was actually in the modal logic, where we tried to open the modal to place a road as soon as we joined the game, and then it got into a  state where it thought it was open, but was not. Hopefully we shouldn't actually lose full points for this.
