### ISSUE TITLE
Map: "Randomly place hexes" still generates the default map

### ISSUE THREAD

**Issue by SierraD012** [cs340tabyu/cs340Winter2017#431]
After creating a new game and selecting "randomly place hexes" on the CreateGameView, the map that is generated appears to be the same as the default map. 
Here's a screenshot of the map that was generated with the "random hexes" option selected. I'm comparing it to the default one shown in the functional specs, and it appears to be the same. I've tested this multiple times with the same result.

![screen shot 2016-10-26 at 10 54 45 pm](https://cloud.githubusercontent.com/assets/21317450/19754993/8cd9bfae-9bcf-11e6-8123-05e22d0a4268.png)

**Comment by dansteren** [comment]
Hum... Could be that we aren't passing the correct data, or that the server isn't working (unlikely), or that we are just not displaying the map correctly. I thought I was passing correct data to the server, but I'm not positive. I'll look into the controller for that.

**Comment by dansteren** [comment]
@Redge-Ballard Please look into the map controller and make sure that you're displaying the data correctly.

**Comment by dansteren** [comment]
I'm sending the right response to the server (as far as I can tell). I think this must be in the way that the map is drawing

**Comment by dansteren** [comment]
I just examined the clientModels of two separate games. I compared the model of a newly created game with that of the default game.  
![clientmodels](https://cloud.githubusercontent.com/assets/5455419/19834160/aeea182c-9e19-11e6-8c67-3f83e3c65bc5.png)
They are definitely different. Here are the maps that were created:

![default-game](https://cloud.githubusercontent.com/assets/5455419/19834147/00f68354-9e19-11e6-9e8f-d3789166968a.png)
![new-game](https://cloud.githubusercontent.com/assets/5455419/19834149/09525bf4-9e19-11e6-9294-eaab30f8df6b.png).

**Comment by dansteren** [comment]
It appears that this only happens when the user only selects random hexes, and not random ports or numbers. Our code is pretty straightforward and so I don't think the error is there. Here's the code:

``` java
String title = getNewGameView().getTitle();
boolean hexes = getNewGameView().getRandomlyPlaceHexes();
boolean numbers = getNewGameView().getRandomlyPlaceNumbers();
boolean ports = getNewGameView().getUseRandomPorts();
Operations.GameOperations.createGame(hexes, numbers, ports, title);
```

So, I'm just passing whatever the user gives us off to the server. So, I'm going to check and see if it's a bug with the server code

**Comment by dansteren** [comment]
Nailed it! I just created a new game on the TAs client and checked only random hexes:
![serversfault](https://cloud.githubusercontent.com/assets/5455419/19834323/8d313dae-9e1f-11e6-9785-37150c22dc22.png)
The map is the exact same. So, it appears to be a bug in the server code. Due to that reason I'm marking this issue as invalid and closing
