### ISSUE TITLE
Players don't receive resources for rolled hexes

### ISSUE THREAD

**Issue by daviscodesbugs** [cs340tabyu/cs340Winter2017#44]
Join a game and play a couple rounds.

If you watch the numbers rolled, you will notice that the player does not always receive resources for the hexes that they have settlements on.

**Comment by daviscodesbugs** [comment]
We've also learned that if a player doesn't have a settlement on a specific resource type, then they end up with negative resources. You can duplicate this issue by not having a settlement on a specific resource type. Roll until a 7 is rolled, then you can see the player's resource values as negative in the discard modal.

**Comment by daviscodesbugs** [comment]
Another symptom: If I do a maritime trade for a negative resource it does increment, but still shows up as "0" in my resource bar until I've traded enough to come out of the negative.

**Comment by rgavinc** [comment]
As far as we know resource collection is calculated at appropriate times by the server. We believe that we have no control over when the players do and do not receive resources.

**Comment by mhnsn** [comment]
This is absolutely an issue and you can control when players do and do not receive resources.

**Comment by csydvs** [comment]
@mhnsn What server endpoint would you suggest that we hit with the logic to allocate resources? I've never seen this happen, and of course if players have negative resources, it's going to display weird, but the only way I know of to get negative resources is by driving the game from swagger. Do you guys allocate resources during your setup phase? If so, how? We're just marking it as invalid because we don't understand the issue, and we've always gotten resources in our tests.

**Comment by daviscodesbugs** [comment]
@csydvs Try placing your initial two settlements in a way that you are not touching a specific hex (i.e. try not touching a wheat hex at all) then just roll until you acquire enough resources that a 7 will force a discard. You can see in the modal that you actually have negative values for that resource. I'll get a screenshot.

**Comment by daviscodesbugs** [comment]
![map](https://cloud.githubusercontent.com/assets/22112533/19819977/61330c3e-9d14-11e6-9eb2-89308a0eea70.png)
In the above game, I am the green player. Of all my settlements, I'm only touching wheat and sheep.  
In the discard modal that pops up (when 7 is rolled) you can see that it lists me as having negative resources. This is actually negative because if I make a maritime trade for it, it comes up to -1, then to 0, and so forth.
![negative_resources](https://cloud.githubusercontent.com/assets/22112533/19820022/92f412c2-9d14-11e6-928c-4c3b26c6e824.png)

**Comment by mhnsn** [comment]
This is what causes the 'steal instead of trade' bug I found. Best we can guess, [speculation]at some point in your code you've got an allocation when a resource is distributed to the correct players, and then a decrement to everyone who shouldn't have it. The decrement is not necessary[/speculation].

**Comment by csydvs** [comment]
@daviscodesbugs @mhnsn Okay, I figured out the issue--we were charging for settlements in the initial rounds. Sorry if I seemed oppositional, but it did seem to me like you guys were pretty out there in suggesting that we directly control the number of resources on the server. Thanks for the clarification!
