### ISSUE TITLE
Game breaks when going through initial setup

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#442]
I believe this issue is closely tied to issue #435. I tried starting a new game and just playing through. I started from the very beginning. I signed in and placed a road for the first player and second player. I then tried to place for the 3rd and the dialog closed after placing a road. It didn't let me place a settlement. So, I looked at player 4 and placed his road and same thing. The game is stuck and I can't continue.

I was doing nothing unexpected during this run through. I was just playing the game like a normal person, so I'm not sure it's possible to have 4 players start a game from scratch and continue.

I will mention that I started up each client with `java -jar catan-client.jar localhost 8081`. I don't know if it's just cause I'm not using your guys' server but I can't get through this initial phase.

**Comment by dansteren** [comment]
**Update:** I shut down client's 3 and 4 and started them up again. After I did that I was able to place the road and settlement for each of them.

**Comment by smithskyler** [comment]
Several bugs are 'duplicates' of this one. By 'duplicate' I mean that the root cause is the same.

That being said, I actually haven't been able to reproduce this specific bug after several tests running it with `java -jar catan-client.jar localhost 8081`. In any case, it looks like it's all being caused by the issue where different clients can sometimes place pieces for other players during setup when all 4 clients are being run on the same computer using a local server.
