### ISSUE TITLE
Game Freezes when a computer rolls a 7

### ISSUE THREAD

**Issue by irbishop** [cs340tabyu/cs340Winter2017#473]
When a computer player rolls a 7 then game hangs and you cannot proceed.
![frozen](https://cloud.githubusercontent.com/assets/161021/19759559/ee13df46-9bea-11e6-87f6-2552fa955eba.png)

**Comment by daviscodesbugs** [comment]
This bug is not readily reproducible, and is probably a symptom of a different bug.
Playing our version of code that is on the google drive, here is a game where an AI rolled a 7 and the game did not freeze. It did not freeze on subsequent AI rolls of 7 either.
![7freeze](https://cloud.githubusercontent.com/assets/22112533/19817823/7c8196c2-9d0a-11e6-9acd-7c2512beca0a.png)

**Comment by dolson25** [comment]
the real bug here is that the discard modal coming up froze our client, so technically it is when an AI rolls a seven and when we have more than 7 cards.  Small difference
