### ISSUE TITLE
Stealing longest road doesn't take away points from the player who previously had it.

### ISSUE THREAD

**Issue by mclements37** [cs340tabyu/cs340Winter2017#567]
![longestroad](https://cloud.githubusercontent.com/assets/21322207/20416485/5ca444f6-acfc-11e6-9ec4-02b93494a15a.JPG)

In the screenshot, player orange stole longest road from player red and gained two victory. Player red, however, did not lose 2 victory for losing longest road. (Note: Player red never played any monuments, so this should have dropped his points to 7 but it still showed him as having 9).

**Comment by smithskyler** [comment]
As it turns out, it does indeed display the wrong number of points because a player's points are only being calculated when they do something that could change the number of points that they have. If red builds a road, or plays a monument, or a soldier, or anything like that, his points recalculate appropriately. Because of this, it would be impossible for Red to win prematurely or anything like that, so this is really just a visual bug. For this reason, I'd call it a P4 or a P5.

**Comment by smithskyler** [comment]
I've fixed this and successfully tested that the victory points shown in the turn tracker update correctly when the longest road is stolen.
