### ISSUE TITLE
Client would not allow me to place my second settlement after exiting then logging back in twice.

### ISSUE THREAD

**Issue by StephBrown923** [cs340tabyu/cs340Winter2017#620]
![screen shot 2016-11-18 at 12 15 57 pm](https://cloud.githubusercontent.com/assets/16596998/20443175/03fd957c-ad89-11e6-8af4-0bdacdbf18cc.png)

**Comment by smithskyler** [comment]
I haven't been able to get this exact bug, but I did get something similar. I clicked to place my settlement during the setup round, and it didn't show up on my screen but it did on everyone else's. If I quit the client and logged back in, everything returned to normal.

In our discussion with the TAs, a bug that can be fixed in this way isn't P2.
