### ISSUE TITLE
Login freeze

### ISSUE THREAD

**Issue by dolson25** [cs340tabyu/cs340Winter2017#637]
Attempting to login incorrectly a few times always leads to a frozen screen

**Comment by klew91** [comment]
You would only get this problem if you are purposefully logging in incorrectly over and over again to try and break it. This is not a P2 because the game doesn't freeze if you login incorrectly a few times. You are blocking the gameplay yourself at that point. Also, I don't think its fair to change the severity of a bug your teammate logged. If they thought it was a P4 then you shouldn't get to change it and make it worse. I agree with the first classification, this is a P4.

**Comment by isaiMercado** [comment]
fixed
