### ISSUE TITLE
It's not anyone's turn

### ISSUE THREAD

**Issue by intcreator** [cs340tabyu/cs340Winter2017#706]
After a couple rounds of playing, each of the four clients says "Not your turn" where the "End turn" button should be.  I restarted each of the clients and they all continue to say that.  None have frozen however.

**Comment by dansteren** [comment]
Same thing happened to me. I played through the first round, second round, and then each player took one turn. When it got back to the first player's turn again, I was stuck and couldn't continue because it said "Not your turn" on all screens. I even restarted player 1's client and it still didn't let me continue.

## Setup:

**Players:** 4 humans, 0 AIs
**Phase:** Normal Gameplay
