### ISSUE TITLE
Longest Road not implemented

### ISSUE THREAD

**Issue by abatschi** [cs340tabyu/cs340Winter2017#778]
When a player has the longest road they dont get the 2 victory points or the symbol next to their name

**Comment by gauntc** [comment]
I was unable to replicate the part where the player doesn't get the victory points.  I was however able to replicate the part where the UI didn't show the award on the turn tracker controller.  That's been fixed, but since I couldn't replicate the victory point discrepancy, that makes this a UI bug and thus not a P3.
